# Generated by Django 4.1.7 on 2023-03-28 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriasProductos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("imagen", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("cantidad", models.IntegerField()),
                ("unidad", models.CharField(max_length=20)),
                ("imagen", models.CharField(max_length=50)),
                ("costo", models.FloatField()),
                ("precio_detal", models.FloatField()),
                ("precio_mayor", models.FloatField()),
                ("precio_especial", models.FloatField()),
                ("categoria", models.ManyToManyField(to="pos.categoriasproductos")),
            ],
        ),
        migrations.CreateModel(
            name="ProductosPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("precio", models.FloatField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pos.producto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("precio_total", models.FloatField()),
                ("productos", models.ManyToManyField(to="pos.productospedido")),
            ],
        ),
    ]
